services:

  grafana:
    image: grafana/grafana@sha256:121a7a9ece6dc10b969f1f96eed64b4f07dfac0d0b8abc070f7cb83bbde86f63
    ports:
      - "${GRAFANA_BIND_ADDRESS:-0.0.0.0}:${GRAFANA_PORT}:3000"

    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}

    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro

    restart: unless-stopped

    networks:
      - observability

  node-exporter:
    image: prom/node-exporter@sha256:9b0ade5e607f9dbedb0a8e11151b6011ae5bd79304c261804cfdd2cadf200a80
    
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'

    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro

    expose:
      - "9100"

    restart: unless-stopped

    networks:
      - observability

  prometheus:
    image: prom/prometheus@sha256:3c42b892cf723fa54d2f262c37a0e1f80aa8c8ddb1da7b9b0df9455a35a7f893

    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'

    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus

    ports:
      - "${PROMETHEUS_BIND_ADDRESS:-127.0.0.1}:${PROMETHEUS_PORT}:9090"

    restart: unless-stopped

    networks:
      - observability

  loki:
    image: grafana/loki@sha256:87f0a067673756a3cede1bcbf0c74875f7df9b09fddb53e399d0c576f756cfcc

    command:
      - "-config.file=/etc/loki/config.yaml"

    volumes:
      - ./loki/config.yaml:/etc/loki/config.yaml:ro
      - loki-data:/loki

    expose:
      - "3100"

    restart: unless-stopped

    networks:
      - observability
  
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.156.0@sha256:125bdbeb7590cc1952c5b3430ecf14063568980c2c93d5b38676cc0446ed8108
    user: "0:0"
    command:
      - "--config=/etc/otelcol/config.yaml"
 
    volumes:
      - ./collector/gateway:/etc/otelcol:ro

    ports:
      - "${GATEWAY_OTLP_GRPC_PORT:-4317}:4317"
      - "${GATEWAY_OTLP_HTTP_PORT:-4318}:4318"

    restart: unless-stopped

    networks:
      - observability

  tempo:
    image: grafana/tempo@sha256:1ce31d6d7ffab62189685e8c47881d4a561c5d38bd0dbd66e40ca83cef07923d

    command:
      - "-config.file=/etc/tempo/config.yaml"

    volumes:
      - ./tempo/config.yaml:/etc/tempo/config.yaml:ro
      - tempo-data:/var/tempo

    expose:
      - "3200"
      - "4317"
      - "4318"

    restart: unless-stopped

    networks:
      - observability

networks:
  observability:

volumes:
  grafana-data:
  prometheus-data:
  tempo-data:
  loki-data:
