error_mode: ignore
log_statements:
  - context: log
    statements:
      - set(resource.attributes["service.name"], log.attributes["service"]) where resource.attributes["service.name"] == nil and log.attributes["service"] != nil
