extensions:
  file_storage/queue:
    directory: /var/lib/otelcol/queue
    create_directory: true

receivers:
  otlp: ${file:/etc/otelcol/config/capabilities/otlp/receiver.yaml}

processors:
  resource/host: ${file:/etc/otelcol/config/common/processors/resource.yaml}
  batch: ${file:/etc/otelcol/config/common/processors/batch.yaml}

exporters:
  otlp_grpc/gateway: ${file:/etc/otelcol/config/common/exporters/gateway-mtls.yaml}

service:
  extensions: [file_storage/queue]
  pipelines:
    logs:
      receivers: [otlp]
      processors: [resource/host, batch]
      exporters: [otlp_grpc/gateway]
    traces:
      receivers: [otlp]
      processors: [resource/host, batch]
      exporters: [otlp_grpc/gateway]
    metrics:
      receivers: [otlp]
      processors: [resource/host, batch]
      exporters: [otlp_grpc/gateway]
