receivers:
  otlp: ${file:/etc/otelcol/ingestion/otlp.yaml}
  receiver_creator/docker_logs: ${file:/etc/otelcol/ingestion/docker-stdout.yaml}
  file_log/local: ${file:/etc/otelcol/ingestion/file-logs.yaml}

processors:
  transform/normalize_json: ${file:/etc/otelcol/normalization/structured-json.yaml}
  transform/normalize_serilog: ${file:/etc/otelcol/normalization/serilog-json.yaml}
  transform/timestamp: ${file:/etc/otelcol/normalization/timestamp.yaml}
  transform/severity: ${file:/etc/otelcol/normalization/severity.yaml}
  transform/service_identity: ${file:/etc/otelcol/enrichment/service-identity.yaml}
  transform/resource_identity: ${file:/etc/otelcol/enrichment/resource-identity.yaml}
  transform/source_provenance: ${file:/etc/otelcol/enrichment/source-provenance.yaml}
  batch: ${file:/etc/otelcol/routing/batch.yaml}

exporters:
  otlp_grpc/tempo: ${file:/etc/otelcol/routing/tempo.yaml}
  otlp_http/loki: ${file:/etc/otelcol/routing/loki.yaml}
  prometheus: ${file:/etc/otelcol/routing/prometheus.yaml}

extensions:
  docker_observer: ${file:/etc/otelcol/ingestion/docker-observer.yaml}

service:
  extensions:
    - docker_observer
  pipelines:
    logs: ${file:/etc/otelcol/service/logs.yaml}
    traces: ${file:/etc/otelcol/service/traces.yaml}
    metrics: ${file:/etc/otelcol/service/metrics.yaml}
